import { writable, type Writable } from 'svelte/store';
import { browser } from '$app/environment';
import { fetchJson, fetchRaw, resolveApiUrl } from 'ui-lib/transport/fetch-helpers';
import type { Library } from 'ui-lib/types/library.type';
import type { YouTubeContent } from 'ui-lib/types/youtube.type';

export interface LibraryServiceState {
	content: YouTubeContent[];
	contentLoading: boolean;
	contentError: string | null;
	favorites: YouTubeContent[];
	favoritesLoading: boolean;
}

const initialState: LibraryServiceState = {
	content: [],
	contentLoading: false,
	contentError: null,
	favorites: [],
	favoritesLoading: false
};

class YouTubeLibraryService {
	public library: Writable<Library | null> = writable(null);
	public state: Writable<LibraryServiceState> = writable(initialState);

	private initialized = false;

	reset(): void {
		this.initialized = false;
		this.library.set(null);
		this.state.set(initialState);
	}

	async initialize(): Promise<void> {
		if (!browser || this.initialized) return;

		try {
			const library = await fetchJson<Library>('/api/libraries');
			this.library.set(library);
			this.initialized = true;
			this.fetchContent();
			this.fetchFavorites();
		} catch (error) {
			console.error('[library] Failed to initialize:', error);
		}
	}

	async fetchContent(): Promise<void> {
		if (!browser) return;

		this.state.update((s) => ({ ...s, contentLoading: true, contentError: null }));

		try {
			const content = await fetchJson<YouTubeContent[]>('/api/youtube/content');
			this.state.update((s) => ({ ...s, content, contentLoading: false }));

			if (content.some((c) => c.durationSeconds == null)) {
				this.fillMissingDurations();
			}
		} catch (error) {
			const errorMsg = error instanceof Error ? error.message : String(error);
			this.state.update((s) => ({ ...s, contentLoading: false, contentError: errorMsg }));
		}
	}

	private async fillMissingDurations(): Promise<void> {
		try {
			const filled = await fetchJson<{ youtubeId: string; durationSeconds: number }[]>(
				'/api/youtube/content/fill-durations',
				{ method: 'POST' }
			);
			if (filled.length === 0) return;
			const map = new Map(filled.map((f) => [f.youtubeId, f.durationSeconds]));
			this.state.update((s) => ({
				...s,
				content: s.content.map((c) =>
					map.has(c.youtubeId) ? { ...c, durationSeconds: map.get(c.youtubeId)! } : c
				)
			}));
		} catch {
			// non-critical
		}
	}

	async fetchFavorites(): Promise<void> {
		if (!browser) return;

		this.state.update((s) => ({ ...s, favoritesLoading: true }));

		try {
			const favorites = await fetchJson<YouTubeContent[]>('/api/youtube/content/favorites');
			this.state.update((s) => ({ ...s, favorites, favoritesLoading: false }));
		} catch {
			this.state.update((s) => ({ ...s, favoritesLoading: false }));
		}
	}

	streamVideoUrl(youtubeId: string): string {
		return resolveApiUrl(`/api/libraries/content/${youtubeId}/stream/video`);
	}

	streamAudioUrl(youtubeId: string): string {
		return resolveApiUrl(`/api/libraries/content/${youtubeId}/stream/audio`);
	}

	streamDownloadVideoUrl(downloadId: string): string {
		return resolveApiUrl(`/api/ytdl/downloads/${downloadId}/stream/video`);
	}

	subtitleUrl(youtubeId: string, lang: string): string {
		return resolveApiUrl(`/api/youtube/content/${youtubeId}/subtitles/${lang}`);
	}

	async listSubtitles(
		youtubeId: string
	): Promise<{ languageCode: string; isAutoGenerated: boolean; fileName: string }[]> {
		try {
			return await fetchJson(`/api/youtube/content/${youtubeId}/subtitles`);
		} catch {
			return [];
		}
	}

	async fetchSubtitles(
		youtubeId: string,
		langs: string[] = []
	): Promise<
		{
			languageCode: string;
			languageName: string;
			isAutoGenerated: boolean;
			filePath: string;
		}[]
	> {
		return fetchJson(`/api/youtube/content/${youtubeId}/subtitles`, {
			method: 'POST',
			body: JSON.stringify({ langs })
		});
	}

	async toggleFavorite(youtubeId: string): Promise<boolean> {
		const result = await fetchJson<{ isFavorite: boolean }>(
			`/api/youtube/content/${youtubeId}/favorite`,
			{
				method: 'PUT'
			}
		);
		this.state.update((s) => ({
			...s,
			content: s.content.map((c) =>
				c.youtubeId === youtubeId ? { ...c, isFavorite: result.isFavorite } : c
			)
		}));
		this.fetchFavorites();
		return result.isFavorite;
	}

	async deleteAudio(youtubeId: string): Promise<void> {
		const response = await fetchRaw(`/api/youtube/content/${youtubeId}/audio`, {
			method: 'DELETE'
		});
		if (!response.ok) throw new Error(`HTTP ${response.status}`);
		await this.fetchContent();
	}

	async deleteVideo(youtubeId: string): Promise<void> {
		const response = await fetchRaw(`/api/youtube/content/${youtubeId}/video`, {
			method: 'DELETE'
		});
		if (!response.ok) throw new Error(`HTTP ${response.status}`);
		await this.fetchContent();
	}
}

export const youtubeLibraryService = new YouTubeLibraryService();
