// @ts-nocheck
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROUTES_DIR = path.resolve(__dirname, "../src/routes");
const OUT_FILE = path.resolve(__dirname, "../src/lib/generated/nav.ts");

const isRouteGroup = (name) => name.startsWith("(") && name.endsWith(")");
const isDynamic = (name) => name.startsWith("[");

function collectRoutes(dir, segments) {
  const out = [];
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return out;
  }

  if (entries.some((e) => e.isFile() && e.name === "+page.svelte")) {
    out.push([...segments]);
  }

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (isDynamic(entry.name)) continue;
    const childDir = path.join(dir, entry.name);
    if (isRouteGroup(entry.name)) {
      out.push(...collectRoutes(childDir, segments));
    } else {
      out.push(...collectRoutes(childDir, [...segments, entry.name]));
    }
  }
  return out;
}

function toLabel(slug) {
  return slug
    .split("-")
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join(" ");
}

function buildNav(routes) {
  const tops = new Map();
  for (const segs of routes) {
    if (segs.length === 0) continue;
    const key = segs[0];
    if (!tops.has(key)) {
      tops.set(key, {
        label: toLabel(key),
        href: "/" + key,
        hasOwnPage: false,
        children: [],
      });
    }
    const item = tops.get(key);
    if (segs.length === 1) {
      item.hasOwnPage = true;
    } else {
      item.children.push({
        label: segs.slice(1).map(toLabel).join(" / "),
        href: "/" + segs.join("/"),
      });
    }
  }
  for (const item of tops.values()) {
    item.children.sort((a, b) => a.label.localeCompare(b.label));
  }
  return Array.from(tops.values()).sort((a, b) =>
    a.label.localeCompare(b.label),
  );
}

export function generate() {
  const routes = collectRoutes(ROUTES_DIR, []);
  const nav = buildNav(routes);

  const body = `// AUTO-GENERATED by scripts/generate-nav.mjs — do not edit by hand.
export type NavChildItem = { label: string; href: string };
export type NavItem = {
\tlabel: string;
\thref: string;
\thasOwnPage: boolean;
\tchildren: NavChildItem[];
};

export const NAV_ITEMS: NavItem[] = ${JSON.stringify(nav, null, "\t")};
`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, body, "utf8");
  return { nav, outFile: OUT_FILE };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { outFile, nav } = generate();
  console.log(`[generate-nav] wrote ${nav.length} top-level entries → ${outFile}`);
}
