import type { ID } from '$types/core.type';

// ===== Playable File =====

export interface PlayableFileSubtitle {
	languageCode: string;
	languageName: string;
	url: string;
	isAutoGenerated: boolean;
}

export interface PlayableFile {
	id: string;
	type: 'youtube' | 'torrent' | 'library';
	name: string;
	outputPath: string;
	mode: 'audio' | 'video';
	format: string | null;
	videoFormat: string | null;
	thumbnailUrl: string | null;
	durationSeconds: number | null;
	size: number;
	completedAt: string;
	subtitles?: PlayableFileSubtitle[];
	infoHash?: string;
}

// ===== Player Display Mode =====

export type PlayerDisplayMode = 'fullscreen' | 'sidebar' | 'inline';

// ===== Player State =====

export type PlayerConnectionState =
	| 'idle'
	| 'connecting'
	| 'signaling'
	| 'streaming'
	| 'error'
	| 'closed';

export interface PlayerState {
	initialized: boolean;
	loading: boolean;
	error: string | null;
	files: PlayableFile[];
	currentFile: PlayableFile | null;
	connectionState: PlayerConnectionState;
	streamServerAvailable: boolean;
	sessionId: string | null;
	localPeerId: string | null;
	remotePeerId: string | null;
	positionSecs: number;
	durationSecs: number | null;
	isSeeking: boolean;
	isPaused: boolean;
	buffering: boolean;
	// When set, PlayerVideo plays this URL directly via <video src> instead of
	// the WebRTC MediaStream path (used by yt-dlp direct streams).
	directStreamUrl: string | null;
	directStreamMimeType: string | null;
	// CID of the firkin currently being played, when known. Drives the
	// consumption tracker — heartbeats only accumulate while this is set
	// (set by playUrl callers that have a firkin context).
	firkinId: string | null;
	// True when a source has been loaded into the player but the caller
	// asked us NOT to start playback automatically (e.g. trailer auto-load).
	// PlayerVideo renders a big centered play overlay in this state; the
	// flag clears as soon as the user clicks it (or playback otherwise
	// begins via `playing` event).
	awaitingPlay: boolean;
	// Poster URL the player should paint immediately, before any stream is
	// loaded. Pages set this on mount when they know a trailer is about to
	// be resolved so the right-side player has something visible from page
	// load. Falls back to `currentFile?.thumbnailUrl` once playback begins.
	posterOverride: string | null;
}

// ===== Player Settings (localStorage) =====

export interface PlayerSettings {
	id: ID;
	preferredVolume: number;
	autoplay: boolean;
}

// ===== Signaling Messages (mirrors Rust's SignalingMessage enum) =====
// Rust uses #[serde(tag = "type", content = "payload")] adjacently tagged format

export type SdpType = 'offer' | 'answer';

export interface SessionDescription {
	sdp_type: SdpType;
	sdp: string;
}

export interface IceCandidate {
	sdp_m_line_index: number;
	candidate: string;
}

export interface SeekCommand {
	position_secs: number;
}

export interface MediaInfoPayload {
	duration_secs: number | null;
}

export interface PositionPayload {
	position_secs: number;
	duration_secs: number | null;
}

export type SignalingMessage =
	| { type: 'SessionDescription'; payload: SessionDescription }
	| { type: 'IceCandidate'; payload: IceCandidate }
	| { type: 'IceGatheringComplete' }
	| { type: 'PeerDisconnected'; payload: { peer_id: string } }
	| { type: 'Seek'; payload: SeekCommand }
	| { type: 'MediaInfo'; payload: MediaInfoPayload }
	| { type: 'PositionUpdate'; payload: PositionPayload };
