use super::detect::Distro;

pub fn install(distro: &Distro) -> Result<(), String> {
    println!("Installing coturn...");
    let cmd = distro.package_manager.install_cmd("coturn");
    run_shell(&cmd)?;
    println!("coturn installed");
    Ok(())
}

pub fn write_config(
    domain: &str,
    shared_secret: &str,
    cert_path: Option<&str>,
    key_path: Option<&str>,
) -> Result<(), String> {
    let mut config = format!(
        r#"# Generated by mhaol-signaling setup
listening-port=3478
tls-listening-port=5349
realm={domain}
use-auth-secret
static-auth-secret={shared_secret}
no-cli
no-multicast-peers
fingerprint
lt-cred-mech
"#
    );

    if let (Some(cert), Some(key)) = (cert_path, key_path) {
        config.push_str(&format!("cert={cert}\npkey={key}\n"));
    }

    std::fs::write("/etc/turnserver.conf", &config)
        .map_err(|e| format!("Failed to write /etc/turnserver.conf: {e}"))?;
    println!("Wrote coturn config to /etc/turnserver.conf");

    // Enable coturn on Debian/Ubuntu (default is disabled)
    let default_file = "/etc/default/coturn";
    if std::path::Path::new(default_file).exists() {
        std::fs::write(default_file, "TURNSERVER_ENABLED=1\n")
            .map_err(|e| format!("Failed to write {default_file}: {e}"))?;
    }

    Ok(())
}

pub fn enable_service() -> Result<(), String> {
    run_shell("systemctl enable coturn")?;
    run_shell("systemctl restart coturn")?;
    println!("coturn service enabled and started");
    Ok(())
}

fn run_shell(cmd: &str) -> Result<(), String> {
    let status = std::process::Command::new("sh")
        .arg("-c")
        .arg(cmd)
        .status()
        .map_err(|e| format!("Failed to run '{cmd}': {e}"))?;
    if !status.success() {
        return Err(format!("Command failed: {cmd}"));
    }
    Ok(())
}
