<script lang="ts">
	import { tick } from 'svelte';
	import classNames from 'classnames';
	import { playerService } from 'ui-lib/services/player.service';
	import { subtitlesService } from 'ui-lib/services/subtitles.service';
	import type {
		PlayableFile,
		PlayableFileSubtitle,
		PlayerConnectionState
	} from 'ui-lib/types/player.type';
	import type { SubtitleSearchContext } from 'ui-lib/types/subtitles.type';
	import PlayerControls from './PlayerControls.svelte';
	import SubtitlesSearchModal from 'ui-lib/components/subtitles/SubtitlesSearchModal.svelte';

	let {
		file = null,
		connectionState = 'idle',
		positionSecs = 0,
		durationSecs = null,
		buffering = false,
		fullscreen = false,
		poster = null,
		subtitleSearchContext = null,
		onprev,
		onnext
	}: {
		file?: PlayableFile | null;
		connectionState?: PlayerConnectionState;
		positionSecs?: number;
		durationSecs?: number | null;
		buffering?: boolean;
		fullscreen?: boolean;
		poster?: string | null;
		subtitleSearchContext?: SubtitleSearchContext | null;
		onprev?: () => void;
		onnext?: () => void;
	} = $props();

	let videoElement = $state<HTMLVideoElement | null>(null);
	let audioElement = $state<HTMLAudioElement | null>(null);
	let streamAttached = $state(false);
	let isFullscreen = $state(false);
	let subsModalOpen = $state(false);
	let textTrackTick = $state(0);
	let audioTrackTick = $state(0);

	const subsState = subtitlesService.state;

	let isVideo = $derived(file?.mode !== 'audio');
	let isStreaming = $derived(connectionState === 'streaming');
	let activeMediaElement = $derived(
		(isVideo ? videoElement : audioElement) as HTMLMediaElement | null
	);
	// Combine subtitles already attached to the file with any downloaded for the search context.
	let assignedSubs = $derived(subtitleSearchContext ? $subsState.assigned : []);
	let combinedSubtitles = $derived<PlayableFileSubtitle[]>([
		...(file?.subtitles ?? []),
		...assignedSubs.map((a) => ({
			languageCode: a.languageCode,
			languageName: a.languageName,
			url: a.url,
			isAutoGenerated: false
		}))
	]);
	let statusLabel = $derived(getStatusLabel(connectionState));
	let effectiveFullscreen = $derived(fullscreen || isFullscreen);

	type AudioTrackLike = { id?: string; label?: string; language?: string; enabled: boolean };
	type VideoElementWithAudio = HTMLVideoElement & {
		audioTracks?: AudioTrackLike[] & {
			length: number;
			addEventListener: (type: string, cb: () => void) => void;
			removeEventListener: (type: string, cb: () => void) => void;
			[index: number]: AudioTrackLike;
		};
	};

	let textTrackOptions = $derived.by(() => {
		void textTrackTick;
		const v = videoElement;
		if (!v) return [] as { index: number; label: string; mode: TextTrackMode }[];
		const out: { index: number; label: string; mode: TextTrackMode }[] = [];
		for (let i = 0; i < v.textTracks.length; i++) {
			const t = v.textTracks[i];
			out.push({
				index: i,
				label: t.label || t.language || `Track ${i + 1}`,
				mode: t.mode
			});
		}
		return out;
	});
	let activeTextTrackIndex = $derived(textTrackOptions.findIndex((t) => t.mode === 'showing'));

	let audioTrackOptions = $derived.by(() => {
		void audioTrackTick;
		const v = videoElement as VideoElementWithAudio | null;
		const tracks = v?.audioTracks;
		if (!tracks || tracks.length <= 1)
			return [] as { index: number; label: string; enabled: boolean }[];
		const out: { index: number; label: string; enabled: boolean }[] = [];
		for (let i = 0; i < tracks.length; i++) {
			const t = tracks[i];
			out.push({
				index: i,
				label: t.label || t.language || `Audio ${i + 1}`,
				enabled: t.enabled
			});
		}
		return out;
	});
	let activeAudioTrackIndex = $derived(audioTrackOptions.findIndex((t) => t.enabled));

	function toggleFullscreen(): void {
		isFullscreen = !isFullscreen;
	}

	function handleFullscreenKeydown(event: KeyboardEvent): void {
		if (event.key === 'Escape') isFullscreen = false;
	}

	$effect(() => {
		if (!isFullscreen) return;
		document.addEventListener('keydown', handleFullscreenKeydown);
		return () => document.removeEventListener('keydown', handleFullscreenKeydown);
	});

	$effect(() => {
		if (isStreaming && !streamAttached) {
			tryAttachStream();
		}
	});

	$effect(() => {
		if (connectionState === 'idle') {
			streamAttached = false;
			isFullscreen = false;
			if (videoElement) {
				videoElement.srcObject = null;
				videoElement.removeAttribute('src');
				videoElement.load();
			}
			if (audioElement) {
				audioElement.srcObject = null;
				audioElement.removeAttribute('src');
			}
		}
	});

	$effect(() => {
		return () => {
			streamAttached = false;
		};
	});

	// Sync the player's subtitle search context with the service.
	$effect(() => {
		subtitlesService.setContext(subtitleSearchContext);
	});

	// Watch for native track list changes so the dropdowns stay in sync.
	$effect(() => {
		const v = videoElement as VideoElementWithAudio | null;
		if (!v) return;
		const onTextTracks = () => {
			textTrackTick++;
		};
		const onAudioTracks = () => {
			audioTrackTick++;
		};
		v.textTracks.addEventListener('addtrack', onTextTracks);
		v.textTracks.addEventListener('removetrack', onTextTracks);
		v.textTracks.addEventListener('change', onTextTracks);
		const audioTracks = v.audioTracks;
		audioTracks?.addEventListener('addtrack', onAudioTracks);
		audioTracks?.addEventListener('removetrack', onAudioTracks);
		audioTracks?.addEventListener('change', onAudioTracks);
		return () => {
			v.textTracks.removeEventListener('addtrack', onTextTracks);
			v.textTracks.removeEventListener('removetrack', onTextTracks);
			v.textTracks.removeEventListener('change', onTextTracks);
			audioTracks?.removeEventListener('addtrack', onAudioTracks);
			audioTracks?.removeEventListener('removetrack', onAudioTracks);
			audioTracks?.removeEventListener('change', onAudioTracks);
		};
	});

	async function tryAttachStream(): Promise<void> {
		// Wait for the DOM to settle after branch switches ({#if isVideo})
		for (let attempt = 0; attempt < 10; attempt++) {
			await tick();
			const stream = playerService.getMediaStream();
			if (!stream) return;

			const element = file?.mode === 'audio' ? audioElement : videoElement;
			if (element) {
				element.srcObject = stream;
				element.play().catch((err: Error) => {
					console.error('[Player] play() failed:', err);
					if (err.name === 'NotAllowedError') {
						playerService.state.update((s) => ({
							...s,
							error: 'Playback blocked by browser. Click play to start.'
						}));
					}
				});
				streamAttached = true;
				return;
			}

			// Element not bound yet -- wait a frame and retry
			await new Promise((r) => requestAnimationFrame(r));
		}
	}

	function handleStop(): void {
		playerService.stop();
		streamAttached = false;
	}

	function handleSeek(positionSecs: number): void {
		playerService.seek(positionSecs);
	}

	function handleSeekStart(): void {
		playerService.setSeeking(true);
	}

	function handleVideoClick(): void {
		if (!activeMediaElement || !isStreaming) return;
		if (activeMediaElement.paused) {
			activeMediaElement.play().catch(console.error);
		} else {
			activeMediaElement.pause();
		}
	}

	function handleWaiting(): void {
		playerService.setBuffering(true);
	}

	function handlePlaying(): void {
		playerService.setBuffering(false);
		playerService.setPaused(false);
	}

	function handleSelectTextTrack(e: Event): void {
		const v = videoElement;
		if (!v) return;
		const value = (e.currentTarget as HTMLSelectElement).value;
		const idx = value === '' ? -1 : parseInt(value, 10);
		for (let i = 0; i < v.textTracks.length; i++) {
			v.textTracks[i].mode = i === idx ? 'showing' : 'disabled';
		}
		textTrackTick++;
	}

	function handleSelectAudioTrack(e: Event): void {
		const v = videoElement as VideoElementWithAudio | null;
		if (!v?.audioTracks) return;
		const idx = parseInt((e.currentTarget as HTMLSelectElement).value, 10);
		for (let i = 0; i < v.audioTracks.length; i++) {
			v.audioTracks[i].enabled = i === idx;
		}
		audioTrackTick++;
	}

	function getStatusLabel(state: PlayerConnectionState): string {
		switch (state) {
			case 'idle':
				return '';
			case 'connecting':
				return 'Connecting to stream server...';
			case 'signaling':
				return 'Negotiating WebRTC connection...';
			case 'streaming':
				return '';
			case 'error':
				return 'Connection failed';
			case 'closed':
				return 'Stream ended';
		}
	}
</script>

<div
	class={classNames({
		'fixed inset-0 z-50 flex flex-col bg-black': isFullscreen,
		'flex h-full flex-col': !isFullscreen && fullscreen
	})}
>
	<div class={effectiveFullscreen ? 'relative min-h-0 flex-1' : 'relative'}>
		{#if isVideo}
			<video
				bind:this={videoElement}
				class={effectiveFullscreen
					? 'h-full w-full cursor-pointer bg-black object-contain'
					: 'w-full cursor-pointer rounded-lg bg-black'}
				playsinline
				poster={poster ?? undefined}
				onclick={handleVideoClick}
				onwaiting={handleWaiting}
				onplaying={handlePlaying}
			>
				{#each combinedSubtitles as sub}
					<track
						kind="subtitles"
						src={sub.url}
						srclang={sub.languageCode}
						label={sub.languageName}
					/>
				{/each}
			</video>

			{#if isStreaming}
				<div class="absolute top-2 right-2 z-10 flex items-center gap-1">
					{#if textTrackOptions.length > 0}
						<select
							class="select-bordered select bg-black/60 select-xs text-white"
							value={String(activeTextTrackIndex)}
							onchange={handleSelectTextTrack}
							aria-label="Subtitles"
						>
							<option value="-1">Subs off</option>
							{#each textTrackOptions as opt}
								<option value={String(opt.index)}>{opt.label}</option>
							{/each}
						</select>
					{/if}
					{#if audioTrackOptions.length > 0}
						<select
							class="select-bordered select bg-black/60 select-xs text-white"
							value={String(activeAudioTrackIndex)}
							onchange={handleSelectAudioTrack}
							aria-label="Audio track"
						>
							{#each audioTrackOptions as opt}
								<option value={String(opt.index)}>{opt.label}</option>
							{/each}
						</select>
					{/if}
					{#if subtitleSearchContext}
						<button
							class="btn border-none bg-black/60 text-white btn-xs hover:bg-black/80"
							aria-label="Search subtitles"
							onclick={() => (subsModalOpen = true)}
						>
							CC
						</button>
					{/if}
				</div>
			{/if}

			{#if buffering}
				<div class="absolute inset-0 flex items-center justify-center rounded-lg bg-black/40">
					<span class="loading loading-lg loading-spinner text-primary"></span>
				</div>
			{/if}
		{:else}
			<div class="flex h-20 items-center justify-center rounded-lg bg-base-300">
				<svg
					xmlns="http://www.w3.org/2000/svg"
					class="h-10 w-10 opacity-30"
					fill="none"
					viewBox="0 0 24 24"
					stroke="currentColor"
				>
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M9 19V6l12-3v13M9 19c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zm12-3c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zM9 10l12-3"
					/>
				</svg>
			</div>
			<audio bind:this={audioElement} class="absolute h-0 w-0 overflow-hidden"></audio>
		{/if}

		{#if !isStreaming && connectionState !== 'idle'}
			<div class="absolute inset-0 flex items-center justify-center rounded-lg bg-base-300/80">
				{#if connectionState === 'connecting' || connectionState === 'signaling'}
					<div class="text-center">
						<span class="loading loading-sm loading-spinner"></span>
						<p class="mt-1 text-xs">{statusLabel}</p>
					</div>
				{:else if connectionState === 'error'}
					<div class="text-center text-error">
						<p class="text-xs font-medium">Connection failed</p>
						<button class="btn mt-1 btn-xs btn-error" onclick={handleStop}> Close </button>
					</div>
				{:else if connectionState === 'closed'}
					<div class="text-center">
						<p class="text-xs opacity-70">Stream ended</p>
					</div>
				{/if}
			</div>
		{/if}
	</div>

	{#if isStreaming}
		<div class={effectiveFullscreen ? 'bg-base-100 p-4' : 'mt-1'}>
			<PlayerControls
				mediaElement={activeMediaElement}
				{isVideo}
				{positionSecs}
				{durationSecs}
				{connectionState}
				isFullscreen={effectiveFullscreen}
				onseek={handleSeek}
				onseekstart={handleSeekStart}
				onstop={handleStop}
				onfullscreentoggle={toggleFullscreen}
				{onprev}
				{onnext}
			/>
		</div>
	{/if}
</div>

<SubtitlesSearchModal
	open={subsModalOpen}
	context={subtitleSearchContext}
	onclose={() => (subsModalOpen = false)}
/>
