import type { ID } from '$types/core.type';
import type { SubsLyricsSyncedLine } from '$types/subs-lyrics.type';

// ===== Playable File =====

export interface PlayableFileSubtitle {
	languageCode: string;
	languageName: string;
	url: string;
	isAutoGenerated: boolean;
}

export interface PlayableFile {
	id: string;
	type: 'youtube' | 'torrent' | 'library';
	name: string;
	outputPath: string;
	mode: 'audio' | 'video';
	format: string | null;
	videoFormat: string | null;
	thumbnailUrl: string | null;
	durationSeconds: number | null;
	size: number;
	completedAt: string;
	subtitles?: PlayableFileSubtitle[];
	infoHash?: string;
}

// ===== Player Display Mode =====

export type PlayerDisplayMode = 'fullscreen' | 'sidebar' | 'inline' | 'navbar';

// ===== Player State =====

export type PlayerConnectionState = 'idle' | 'connecting' | 'streaming' | 'error' | 'closed';

export interface PlayerState {
	initialized: boolean;
	loading: boolean;
	error: string | null;
	files: PlayableFile[];
	currentFile: PlayableFile | null;
	connectionState: PlayerConnectionState;
	positionSecs: number;
	durationSecs: number | null;
	isSeeking: boolean;
	isPaused: boolean;
	buffering: boolean;
	// When set, PlayerVideo plays this URL directly via <video src> instead of
	// the WebRTC MediaStream path (used by yt-dlp direct streams).
	directStreamUrl: string | null;
	directStreamMimeType: string | null;
	// Source-time offset (seconds) corresponding to `videoElement.currentTime
	// === 0`. Defaults to 0; set to non-zero by IPFS-stream "seek-anywhere"
	// session restarts so the player's seek bar / buffered ranges /
	// current-time display all stay in *source* time even though the
	// underlying HLS playlist starts at a non-zero source timestamp.
	streamOffsetSecs: number;
	// CID of the firkin currently being played, when known. Drives the
	// consumption tracker — heartbeats only accumulate while this is set
	// (set by playUrl callers that have a firkin context).
	firkinId: string | null;
	// Optional per-track id within the firkin (e.g. MusicBrainz track id).
	// When set, consumption is bucketed against (firkin, track, user) so the
	// consumption page can break down listening time per song. Movies / TV /
	// single-file streams leave this null.
	trackId: string | null;
	// Display title for the active track. Captured alongside trackId so the
	// consumption row can be labelled without re-resolving the album.
	trackTitle: string | null;
	// Synced LRC lines for the currently-playing track, when available.
	// Drives the navbar lyrics panel; null disables the panel.
	syncedLyrics: SubsLyricsSyncedLine[] | null;
	// Seek target to apply once the media element fires `loadedmetadata`.
	// Used by snapshot restoration to land at the saved position after a
	// page refresh; cleared by the player component once applied.
	pendingSeekSecs: number | null;
}

// ===== Player Playlist =====
//
// An optional queue of tracks the user can swap between from the floating
// player panel. Lives alongside (not inside) PlayerState so that internal
// `beginLoad`/`playUrl` cycles can swap the active track without wiping
// the whole queue. Only an explicit `playerService.stop()` clears it.

export interface PlaylistTrack {
	title: string;
	// `null` means the track exists in the listing but isn't playable
	// (no resolved YouTube URL). The row renders disabled.
	youtubeUrl: string | null;
	thumbnailUrl: string | null;
	durationSeconds: number | null;
	syncedLyrics: SubsLyricsSyncedLine[] | null;
	position?: number;
	// Stable per-track identifier (e.g. MusicBrainz track id). Surfaces
	// through the player into the consumption tracker so each song gets
	// its own row.
	id?: string;
}

export interface PlayerPlaylist {
	tracks: PlaylistTrack[];
	currentIndex: number;
	title?: string;
	// CID of the firkin (album) this playlist was sourced from. Set by the
	// catalog tracks card so the navbar prev/next swap stays in the same
	// firkin context for consumption tracking.
	firkinId?: string;
}

// ===== Player Settings (localStorage) =====

export interface PlayerSettings {
	id: ID;
	preferredVolume: number;
	autoplay: boolean;
}

// ===== Player Snapshot (localStorage) =====
//
// Restorable view of what's in the bottom-right navbar player. Persisted
// on every state change (throttled) so a page refresh can rehydrate the
// panel — the playing track, the playlist, and the seek position. YouTube
// stream URLs expire, so the restore path re-resolves from the file id
// rather than trusting `directStreamUrl` for those.

export interface PlayerSnapshot {
	displayMode: PlayerDisplayMode;
	currentFile: PlayableFile | null;
	positionSecs: number;
	directStreamUrl: string | null;
	directStreamMimeType: string | null;
	firkinId: string | null;
	trackId: string | null;
	trackTitle: string | null;
	syncedLyrics: SubsLyricsSyncedLine[] | null;
	playlist: PlayerPlaylist | null;
}
