<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { apiUrl } from 'ui-lib/lib/api-base';
	import { youtubeService } from 'ui-lib/services/youtube.service';
	import { youtubeLibraryService } from 'ui-lib/services/youtube-library.service';
	import { mediaModeService } from 'ui-lib/services/media-mode.service';
	import type { YouTubeChannelMeta, SubtitleTrack } from 'ui-lib/types/youtube.type';
	import type { YouTubeSearchChannelItem } from 'ui-lib/types/youtube-search.type';
	import type { RightPanelVideo } from 'ui-lib/types/youtube.type';
	import VideoDetailPage from 'ui-lib/components/youtube/VideoDetailPage.svelte';

	let id = $derived($page.params.id ?? '');

	const ytState = youtubeService.state;
	const libState = youtubeLibraryService.state;
	const mediaModeStore = mediaModeService.store;
	let mediaMode = $derived<'audio' | 'video'>($mediaModeStore ?? 'video');

	let video = $state<RightPanelVideo | null>(null);
	let loading = $state(true);

	// YouTube state
	let ytChannelMeta = $state<YouTubeChannelMeta | null>(null);
	let ytStreamUrl = $state<string | null>(null);
	let ytStreamMimeType = $state<string | null>(null);
	let ytStreamLoading = $state(false);
	let ytStreamError = $state(false);
	let ytAvailableTracks = $state<SubtitleTrack[]>([]);
	let ytDownloadedLangs = $state<Set<string>>(new Set());
	let ytActiveSubLang = $state<string | null>(null);
	let ytFetchingSubs = $state(false);
	let ytDownloadingAudio = $state(false);
	let ytDownloadingVideo = $state(false);
	let ytTogglingFavorite = $state(false);
	let ytDeletingAudio = $state(false);
	let ytDeletingVideo = $state(false);

	let ytLiveContent = $derived(
		video ? ($libState.content.find((c) => c.youtubeId === video!.videoId) ?? null) : null
	);
	let ytHasVideo = $derived(ytLiveContent?.hasVideo ?? false);
	let ytHasAudio = $derived(ytLiveContent?.hasAudio ?? false);
	let ytVideoSrc = $derived(
		ytHasVideo && video ? youtubeLibraryService.streamVideoUrl(video.videoId) : null
	);
	let ytIsFavorite = $derived(ytLiveContent?.isFavorite ?? false);

	let ytVideoDownloads = $derived(
		video ? $ytState.downloads.filter((d) => d.videoId === video!.videoId) : []
	);
	let ytActiveDownload = $derived(
		ytVideoDownloads.find((d) =>
			['pending', 'fetching', 'downloading', 'muxing'].includes(d.state)
		) ??
			ytVideoDownloads.at(-1) ??
			null
	);
	let ytAudioInProgress = $derived(
		ytVideoDownloads.some(
			(d) =>
				(d.mode === 'audio' || d.mode === 'both') &&
				['pending', 'fetching', 'downloading', 'muxing'].includes(d.state)
		)
	);
	let ytVideoInProgress = $derived(
		ytVideoDownloads.some(
			(d) =>
				(d.mode === 'video' || d.mode === 'both') &&
				['pending', 'fetching', 'downloading', 'muxing'].includes(d.state)
		)
	);

	let ytSubtitlesForPlayer = $derived<
		{ languageCode: string; languageName: string; url: string; isAutoGenerated: boolean }[]
	>(
		ytActiveSubLang && video
			? [
					{
						languageCode: ytActiveSubLang,
						languageName:
							ytAvailableTracks.find((t) => t.languageCode === ytActiveSubLang)?.languageName ??
							ytActiveSubLang,
						url: youtubeLibraryService.subtitleUrl(video.videoId, ytActiveSubLang),
						isAutoGenerated:
							ytAvailableTracks.find((t) => t.languageCode === ytActiveSubLang)?.isAutoGenerated ??
							false
					}
				]
			: []
	);

	let ytChannelItem = $derived<YouTubeSearchChannelItem | null>(
		video?.uploaderName
			? {
					type: 'channel',
					channelId: ytChannelMeta?.channelId ?? video.uploaderUrl?.split('/').pop() ?? '',
					name: video.uploaderName,
					thumbnail: ytChannelMeta?.avatar ?? video.uploaderAvatar ?? '',
					url: video.uploaderUrl ?? '',
					subscriberText: ytChannelMeta?.subscriberText ?? '',
					videoCountText: '',
					description: ytChannelMeta?.description ?? '',
					verified: video.uploaderVerified ?? false
				}
			: null
	);

	// Fetch subtitles and channel meta when video changes
	$effect(() => {
		const v = video;
		ytActiveSubLang = null;
		ytAvailableTracks = [];
		ytDownloadedLangs = new Set();

		if (!v) return;

		fetch(
			apiUrl(
				`/api/ytdl/info/video?url=${encodeURIComponent(`https://www.youtube.com/watch?v=${v.videoId}`)}`
			)
		)
			.then((res) => (res.ok ? res.json() : null))
			.then((info: { subtitleTracks?: SubtitleTrack[] } | null) => {
				if (info?.subtitleTracks) ytAvailableTracks = info.subtitleTracks;
			})
			.catch(() => {});

		if (ytHasVideo || ytHasAudio) {
			youtubeLibraryService.listSubtitles(v.videoId).then((subs) => {
				ytDownloadedLangs = new Set(subs.map((s) => s.languageCode));
			});
		}
	});

	// Fetch stream URL if no local file
	$effect(() => {
		const v = video;
		const hasLocalVideo = ytHasVideo;
		const hasLocalAudio = ytHasAudio;
		const mode = mediaMode;
		const needsStream =
			v && !((mode === 'video' && hasLocalVideo) || (mode === 'audio' && hasLocalAudio));
		if (needsStream && v) {
			ytStreamLoading = true;
			ytStreamError = false;
			ytStreamUrl = null;
			youtubeService.fetchStreamUrls(v.videoId).then((result) => {
				if (!result) {
					ytStreamError = true;
					ytStreamLoading = false;
					return;
				}
				const best = youtubeService.selectBestMuxedFormat(result);
				if (best) {
					ytStreamUrl = best.url;
					ytStreamMimeType = best.mimeType;
				} else {
					ytStreamError = true;
				}
				ytStreamLoading = false;
			});
		} else {
			ytStreamUrl = null;
			ytStreamLoading = false;
			ytStreamError = false;
		}
	});

	// Fetch channel meta
	$effect(() => {
		const url = video?.uploaderUrl;
		ytChannelMeta = null;
		if (!url) return;
		const handle = url.split('/').pop();
		if (!handle) return;
		fetch(apiUrl(`/api/youtube/channel-meta?handle=${handle}`))
			.then((res) => (res.ok ? res.json() : null))
			.then((data: YouTubeChannelMeta | null) => {
				ytChannelMeta = data;
			})
			.catch(() => {});
	});

	async function handleSubtitleSelect(lang: string | null) {
		if (!video) return;
		if (lang === null) {
			ytActiveSubLang = null;
			return;
		}
		if (!ytDownloadedLangs.has(lang)) {
			ytFetchingSubs = true;
			try {
				await youtubeLibraryService.fetchSubtitles(video.videoId, [lang]);
				ytDownloadedLangs = new Set([...ytDownloadedLangs, lang]);
			} catch (e) {
				console.error('[VideoDetail] Failed to fetch subtitle:', e);
				ytFetchingSubs = false;
				return;
			}
			ytFetchingSubs = false;
		}
		ytActiveSubLang = lang;
	}

	async function handleDownload(mode: 'audio' | 'video') {
		if (!video) return;
		if (mode === 'audio') ytDownloadingAudio = true;
		else ytDownloadingVideo = true;
		await youtubeService.queueDownloadWithMode(video.videoId, video.title, video.thumbnail, mode);
		if (mode === 'audio') ytDownloadingAudio = false;
		else ytDownloadingVideo = false;
	}

	async function handleToggleFavorite() {
		if (!video || ytTogglingFavorite) return;
		ytTogglingFavorite = true;
		await youtubeLibraryService.toggleFavorite(video.videoId);
		ytTogglingFavorite = false;
	}

	async function handleDeleteAudio() {
		if (!video) return;
		ytDeletingAudio = true;
		await youtubeLibraryService.deleteAudio(video.videoId);
		ytDeletingAudio = false;
	}

	async function handleDeleteVideo() {
		if (!video) return;
		ytDeletingVideo = true;
		await youtubeLibraryService.deleteVideo(video.videoId);
		ytDeletingVideo = false;
	}

	onMount(() => {
		// Build a RightPanelVideo from the video ID
		// Try to find it in the library first
		const libContent = $libState.content.find((c) => c.youtubeId === id);
		if (libContent) {
			video = {
				videoId: id,
				title: libContent.title,
				thumbnail: libContent.thumbnailUrl ?? '',
				hasVideo: libContent.hasVideo,
				hasAudio: libContent.hasAudio
			};
		} else {
			// Minimal video object — details will be fetched via effects
			video = {
				videoId: id,
				title: '',
				thumbnail: ''
			};
			// Fetch info to get title
			fetch(
				apiUrl(
					`/api/ytdl/info/video?url=${encodeURIComponent(`https://www.youtube.com/watch?v=${id}`)}`
				)
			)
				.then((res) => (res.ok ? res.json() : null))
				.then(
					(
						info: {
							title?: string;
							thumbnail?: string;
							uploaderName?: string;
							uploaderUrl?: string;
							viewCount?: number;
							uploadDate?: string;
						} | null
					) => {
						if (info) {
							video = {
								videoId: id,
								title: info.title ?? '',
								thumbnail: info.thumbnail ?? '',
								uploaderName: info.uploaderName,
								uploaderUrl: info.uploaderUrl,
								views: info.viewCount,
								viewsText: info.viewCount
									? `${info.viewCount.toLocaleString()} views`
									: undefined,
								publishedText: info.uploadDate
							};
						}
					}
				)
				.catch(() => {});
		}
		loading = false;
	});
</script>

{#if video && video.title}
	<VideoDetailPage
		{video}
		channelItem={ytChannelItem}
		{mediaMode}
		videoSrc={ytVideoSrc}
		streamUrl={ytStreamUrl}
		streamLoading={ytStreamLoading}
		streamError={ytStreamError}
		streamMimeType={ytStreamMimeType}
		subtitlesForPlayer={ytSubtitlesForPlayer}
		availableTracks={ytAvailableTracks}
		downloadedLangs={ytDownloadedLangs}
		activeSubLang={ytActiveSubLang}
		fetchingSubs={ytFetchingSubs}
		hasVideo={ytHasVideo}
		hasAudio={ytHasAudio}
		isFavorite={ytIsFavorite}
		activeDownload={ytActiveDownload}
		audioInProgress={ytAudioInProgress}
		videoInProgress={ytVideoInProgress}
		liveContent={ytLiveContent}
		downloadingAudio={ytDownloadingAudio}
		downloadingVideo={ytDownloadingVideo}
		togglingFavorite={ytTogglingFavorite}
		deletingAudio={ytDeletingAudio}
		deletingVideo={ytDeletingVideo}
		ondownloadaudio={() => handleDownload('audio')}
		ondownloadvideo={() => handleDownload('video')}
		ontogglefavorite={handleToggleFavorite}
		ondeleteaudio={handleDeleteAudio}
		ondeletevideo={handleDeleteVideo}
		onselectsubtitle={handleSubtitleSelect}
		onback={() => goto('/youtube')}
	/>
{:else if loading}
	<div class="flex flex-1 items-center justify-center">
		<span class="loading loading-lg loading-spinner"></span>
	</div>
{:else}
	<div class="flex flex-1 items-center justify-center">
		<span class="loading loading-lg loading-spinner"></span>
	</div>
{/if}
